spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/StudyOps
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      #hbm2ddl.auto: update
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  default-produces-media-type: application/json

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

